stages:
  - build
  - deploy

variables:
  BATCH_BUILD: "1"
  V: "0"
  IDF_CI_BUILD: "1"

before_script:
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git --version
  - git submodule update --init --recursive --force

.build_examples_template: &build_examples_template
  stage: build
  image: espressif/idf:release-v4.4
  tags:
    - build

build_demo_cmake:
  <<: *build_examples_template
  script:
    - idf.py fullclean
    - idf.py build
    - idf.py fullclean
    - idf.py set-target esp32s2
    - idf.py build
    - idf.py fullclean
    - idf.py set-target esp32s3
    - idf.py build

build_docs:
    stage: build
    image: $CI_SPHINX_DOCKER:latest
    tags:
        - build_docs
    artifacts:
        when: always
        paths:
            # English version of documentation
            - docs/en/rst/sphinx-warning-log.txt
            - docs/en/rst/_build/html
            # Chinese version of documentation
            - docs/zh_CN/rst/sphinx-warning-log.txt
            - docs/zh_CN/rst/_build/html
        expire_in: 1 week
    before_script:
      - echo "skip default before_script"
    script:
      - cd docs
      # make English version of documentation
      - cd en/
      - cd rst/
      - make clean && make html
      - cd ../../
      # make Chinese version of documentation
      - cd zh_CN/
      - cd rst/
      - make clean && make html
      - cd ../../

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v/
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-drone.git
    # What the next line of script does: goes through the list of refs for all branches we push to github,
    # generates a snippet of shell which is evaluated. The snippet checks CI_BUILD_REF against the SHA
    # (aka objectname) at tip of each branch, and if any SHAs match then it checks out the local branch
    # and then pushes that ref to a corresponding github branch
    #
    # NB: In gitlab 9.x, CI_BUILD_REF was deprecated. New name is CI_COMMIT_SHA. If below command suddenly
    # generates bash syntax errors, this is probably why.
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_COMMIT_SHA == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)